version: "3.9"

services:
  app:
    image: php:8.4-apache
    container_name: crochet_critters
    ports:
      - "8000:80" # maps container port 80 to Windows port 8000
    volumes:
      - ./crochet-critters:/var/www/html
    working_dir: /var/www/html
    tty: true
    command: >
      bash -c "
      apt-get update && 
      apt-get install -y libicu-dev zip unzip git libzip-dev && 
      docker-php-ext-install intl zip && 
      php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\" &&
      php composer-setup.php --install-dir=/usr/local/bin --filename=composer &&
      php -r \"unlink('composer-setup.php');\" &&
      composer install --prefer-dist &&
      apache2-foreground
      "
